spring:
  application:
    name: mail-notifier-service

management:

  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
  info:
    env:
      enabled: true

  endpoint: 
    health: 
      show-details: always

info:
  application:
    groupId: '@project.groupId@'
    artifactId: '@project.artifactId@'
    version: '@project.version@'


app:
  mail-settings:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    connectionTimeout: 5000
    timeout: 3000
    writeTimeout: 3000


send:
  mail: ${CORREO_PRUEBA}
  password: ${PASSWORD}

